version: '3.8'
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=vinsguru
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=userdb
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  mongodb_data_container: